language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t shreyas04/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shreyas04/docker-react npm run test